version: '3'

services:

  app:
    build: .
    volumes:
      - .:/code

    working_dir: /code

    ports:
      - 8000:8000

    command: bash -c "pelican content -s pelicanconf.py && cd output && python -m http.server 8000"

